DECLARE @ASSESSMENT_ID INT = 3625

DECLARE @FACILITY_OUTPUT TABLE (NAME VARCHAR(MAX),STREETADDRESS VARCHAR(MAX),CITY VARCHAR(MAX),COUNTRY_ID INT,STATEPROVINCE VARCHAR(MAX),ZIP VARCHAR(MAX),FACILITYYPE INT,DESCRIPTION VARCHAR(MAX),COMMENTS VARCHAR(MAX),INACTIVE BIT)
SELECT DISTINCT 'INSERT INTO @FACILITY_OUTPUT VALUES ('''+REPLACE(A.Name,'''','''''')+''','''+REPLACE(A.StreetAddress,'''','''''')+''','''+A.City+''','+CAST(A.CountryId AS VARCHAR(256))+','''+A.StateProvince+''','''+A.Zip+''','''+CAST(A.FacilityTypeId AS VARCHAR(256))+''','''+COALESCE(REPLACE(A.Description,'''',''''''),'')+''','''+COALESCE(REPLACE(A.Comments,'''',''''''),'')+''','+CAST(A.Inactive AS VARCHAR(256))+');'
FROM Facility A
WHERE
	A.SubscriberId = (SELECT B.SubscriberId FROM CSFAssessment B WHERE B.Id = @ASSESSMENT_ID)

DECLARE @LINKED_FACILITIES TABLE (NAME VARCHAR(MAX))
SELECT DISTINCT 'INSERT INTO @LINKED_FACILITIES VALUES ('''+B.Name+''');'
FROM CSFAssessmentFacility A
JOIN Facility B ON B.Id = A.FacilityId
WHERE
	A.CSFAssessmentId = @ASSESSMENT_ID
	