SET NOCOUNT ON

/*

READ: THIS SCRIPT NEEDS THE OUTPUTS FROM THE 01_facilities and 02_systems

*/

--NECESSARY VARS
--DECLARE @SUBSCRIBER INT = 5151
DECLARE @ASSESSMENT_ID INT = 14335


DECLARE @DOCUMENT_OUTPUT TABLE (NAME VARCHAR(MAX),DESCRIPTION VARCHAR(MAX),DOCUMENT_ID INT)
DECLARE @DOCUMENTS_REQUIREMENTS TABLE (DOCUMENT VARCHAR(MAX),BUID VARCHAR(MAX),LINK_TYPE INT, POLICY BIT,PROCESS BIT,IMPLEMENTED BIT, MEASURED BIT, MANAGED BIT, OPORIND VARCHAR(10))

-- INSERT DOCUMENT OUTPUT
INSERT INTO @DOCUMENT_OUTPUT VALUES ('aaaa','02/19/2020','1')
INSERT INTO @DOCUMENT_OUTPUT VALUES ('MyCSF.zip','','1')
INSERT INTO @DOCUMENT_OUTPUT VALUES ('MyCSF.zip','02/19/2020','1')
INSERT INTO @DOCUMENT_OUTPUT VALUES ('New Doc Bug Test','Description','1')
INSERT INTO @DOCUMENT_OUTPUT VALUES ('POLICY 1.pdf','','1')
INSERT INTO @DOCUMENT_OUTPUT VALUES ('Policy 4.docx','','1')
INSERT INTO @DOCUMENT_OUTPUT VALUES ('Policy 4.pdf','','1')
INSERT INTO @DOCUMENT_OUTPUT VALUES ('Test Plan 1.xlsx','','1')
INSERT INTO @DOCUMENT_OUTPUT VALUES ('Test','','1')


-- INSERT DOCUMENTS REQUIREMENTS
INSERT INTO @DOCUMENTS_REQUIREMENTS VALUES ('aaaa','0107.02d1Organizational.1',1,1,1,0,0,0,'')
INSERT INTO @DOCUMENTS_REQUIREMENTS VALUES ('MyCSF.zip','0501.09m1Organizational.1',1,1,1,1,1,1,'O')
INSERT INTO @DOCUMENTS_REQUIREMENTS VALUES ('MyCSF.zip','0601.06g1Organizational.124',1,0,0,0,0,0,'')
INSERT INTO @DOCUMENTS_REQUIREMENTS VALUES ('Policy 4.docx','0101.00a1Organizational.123',1,0,0,0,0,0,'')
INSERT INTO @DOCUMENTS_REQUIREMENTS VALUES ('Policy 4.docx','0104.02a1Organizational.12',1,0,0,0,0,0,'')
INSERT INTO @DOCUMENTS_REQUIREMENTS VALUES ('Test','0107.02d1Organizational.1',1,1,1,0,0,0,'')


-- INSERT DOCUMENT INTO ASSESSMENT
INSERT INTO CSFAssessmentDocument
	SELECT @ASSESSMENT_ID,A.DOCUMENT_ID,A.NAME,A.DESCRIPTION,NULL,NULL,NULL,GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL
	FROM @DOCUMENT_OUTPUT A
	LEFT JOIN CSFAssessmentDocument B ON B.Name = A.NAME AND B.Description = A.DESCRIPTION AND B.CSFAssessmentId = @ASSESSMENT_ID
	WHERE
		B.Id IS NULL


-- LINK DOCUMENTS TO STATEMENTS
INSERT INTO CSFAssessmentRequirementDocument
	SELECT F.Id,B.Id,A.IMPLEMENTED,A.MANAGED,A.MEASURED,A.POLICY,A.PROCESS,A.OPORIND,GETDATE(),A.LINK_TYPE
	FROM @DOCUMENTS_REQUIREMENTS A
	JOIN CSFAssessmentDocument B ON B.Name = A.DOCUMENT AND B.CSFAssessmentId = @ASSESSMENT_ID
	JOIN CSFQuestionRequirement C ON C.BaselineUniqueId = A.BUID
	JOIN CSFAssessmentDomain D ON D.Id = C.CSFAssessmentDomainId AND D.VersionId = (SELECT VersionId FROM CSFAssessment WHERE Id = @ASSESSMENT_ID)
	JOIN CSFAssessmentRequirement F ON F.CSFQuestionRequirementId = C.Id AND F.CSFAssessmentId = @ASSESSMENT_ID
	LEFT JOIN CSFAssessmentRequirementDocument E ON E.CSFAssessmentRequirementId = F.Id AND E.CSFAssessmentDocumentId = B.Id
	WHERE
		E.CSFAssessmentDocumentId IS NULL
